substitutions:
  name: candle
  friendly_name: Candle
  alpha: 90%
  intensity: 4%
  default_transition_length: 0.5s
  frequency: 1000 Hz

esphome:
  name: ${name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  reboot_timeout: 0s
  manual_ip:
    static_ip: !secret ip_candle
    gateway: !secret ip_router
    subnet: !secret ip_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret esphome_fallback_hotspot_pass

# captive_portal:

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_encryption_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret esphome_ota_pass

light:
  - platform: monochromatic
    name: ${friendly_name}
    id: candle
    output: candle_pwm
    default_transition_length: ${default_transition_length}
    effects:
      - flicker:
          name: Flicker
          alpha: ${alpha}
          intensity: ${intensity}
      - flicker:
          name: Flicker2
          alpha: ${alpha}
          intensity: 1.5%

output:
  - platform: esp8266_pwm
    id: candle_pwm
    pin: D1
    frequency: $frequency
