binary_sensor:
  - platform: template
    sensors:
      # is computer at desk
      disrupted_mba_at_desk:
        friendly_name: "At Desk"
        device_class: presence
        value_template: "{{ is_state('device_tracker.disrupted_mba', 'home') and states('sensor.disrupted_mba_displays') | int > 1 or is_state('sensor.disrupted_mba_primary_display_name', 'DELL P2415Q') }}"

sensor:
  - platform: history_stats
    name: disrupted-MBA usage today
    entity_id: binary_sensor.disrupted_mba_active
    state: "on"
    type: time
    start: "{{ now().replace(hour=8, minute=0, second=0) }}"
    # start: '{{ (as_timestamp(now().replace(hour=20, minute=0, second=0)) - 24 * 3600) }}'
    end: "{{ now() }}"
    # duration:
    #   hours: 16

automation:
  - id: light_desk_computeer
    alias: light desk computer
    trigger:
      - platform: state
        entity_id: binary_sensor.disrupted_mba_active
      - platform: state
        entity_id: binary_sensor.disrupted_mba_at_desk
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
          - condition: state
            entity_id: light.desk_lamp
            state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.desk_lamp
                state: "off"
              - condition: state
                entity_id: binary_sensor.disrupted_mba_active
                state: "on"
              - condition: state
                entity_id: binary_sensor.disrupted_mba_at_desk
                state: "on"
            sequence:
              - service: light.turn_on
                data_template:
                  entity_id: light.desk_lamp
                  color_temp: "{{ states('sensor.adaptive_colortemp') }}"
          - conditions:
              - condition: state
                entity_id: light.desk_lamp
                state: "on"
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.disrupted_mba_active
                    state: "off"
                  - condition: state
                    entity_id: binary_sensor.disrupted_mba_at_desk
                    state: "off"
            sequence:
              - service: light.turn_off
                data:
                  entity_id: light.desk_lamp
