automation:
  - id: music_kitchen_lofi
    alias: music kitchen lofi
    trigger: []
    condition: []
    action:
      - service: media_player.play_media
        target:
          entity_id: media_player.kitchen_speaker
        data:
          media_content_type: "music"
          media_content_id: "spotify:playlist:66YQDZDPxIAotL6fOID7BJ"
      - service: media_player.shuffle_set
        target:
          entity_id: media_player.kitchen_speaker
        data:
          shuffle: true

  - id: music_kitchen_reset_shuffle
    alias: music kitchen reset shuffle
    trigger:
      - platform: state
        entity_id: media_player.kitchen_speaker
        from: "playing"
        to: "paused"
    condition:
      - condition: template
        value_template: '{{ is_state_attr("media_player.kitchen_speaker", "shuffle", false) }}'
    action:
      - service: media_player.shuffle_set
        target:
          entity_id: media_player.kitchen_speaker
        data:
          shuffle: false
