# use Desk remote to control volume on active players
automation:
  - alias: remote google home volume increase
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_short_press
        subtype: right
    condition:
      - condition: state
        entity_id: media_player.google_home
        state: "playing"
      - condition: template
        value_template: "{{ state_attr('media_player.google_home', 'volume_level') | float <= 0.45 }}"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.google_home', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.google_home
        data_template:
          volume_level: "{{ state_attr('media_player.google_home', 'volume_level') | float + 0.05 }}"

  - alias: remote google home volume decrease
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_short_press
        subtype: left
    condition:
      - condition: state
        entity_id: media_player.google_home
        state: "playing"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.google_home', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.google_home
        data_template:
          volume_level: "{{ state_attr('media_player.google_home', 'volume_level') | float - 0.05 }}"

  - alias: remote kodi volume increase
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_short_press
        subtype: right
    condition:
      - condition: state
        entity_id: media_player.kodi
        state: "playing"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.kodi', 'volume_level') | float <= 0.95 }}"
      - condition: template
        value_template: "{{ state_attr('media_player.kodi', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.kodi
        data_template:
          volume_level: "{{ state_attr('media_player.kodi', 'volume_level') | float + 0.05 }}"

  - alias: remote kodi volume decrease
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_short_press
        subtype: left
    condition:
      - condition: state
        entity_id: media_player.kodi
        state: "playing"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.kodi', 'volume_level') | float > 0.05 }}"
      - condition: template
        value_template: "{{ state_attr('media_player.kodi', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.kodi
        data_template:
          volume_level: "{{ state_attr('media_player.kodi', 'volume_level') | float - 0.05 }}"

  - alias: remote google home skip next
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_long_press
        subtype: right
    condition:
      - condition: state
        entity_id: media_player.google_home
        state: "playing"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.google_home', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.google_home

  - alias: remote google home skip previous
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_long_press
        subtype: left
    condition:
      - condition: state
        entity_id: media_player.google_home
        state: "playing"
      # - condition: template
      #   value_template: "{{ state_attr('media_player.google_home', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.google_home

  - alias: remote kodi skip next
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_long_press
        subtype: right
    condition:
      - condition: state
        entity_id: media_player.kodi
        state: "playing"
      - condition: template
        value_template: "{{ state_attr('media_player.kodi', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.kodi

  - alias: remote kodi skip previous
    trigger:
      - platform: device
        domain: zha
        device_id: 3c43ca013a444ac7be79e75622ad2310
        type: remote_button_long_press
        subtype: left
    condition:
      - condition: state
        entity_id: media_player.kodi
        state: "playing"
      - condition: template
        value_template: "{{ state_attr('media_player.kodi', 'media_content_type') in ['music'] }}"
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.kodi
