# homeassistant:
#   customize_glob:
#     sensor.radarr_*:
#       icon: mdi:movie
#   customize:
#     switch.transmission_turtle_mode:
#       icon: mdi:gauge-empty

nzbget:
  host: !secret ip_vault
  username: !secret nzbget_user
  password: !secret nzbget_password
  monitored_variables:
    - "download_rate"
  scan_interval: 30

rtorrent:
  url: !secret rtorrent_url
  monitored_variables:
    # - "current_status"
    - "download_speed"
    - "upload_speed"
    - "upload_limit"
    - "download_limit"
    - "all_torrents"
    # - "stopped_torrents"
    # - "complete_torrents"
    - "uploading_torrents"
    - "downloading_torrents"
    - "active_torrents"
  scan_interval: 30

sensor:
  # - platform: rest
  #   name: Wireguard
  #   resource: http://a0d7b954-wireguard
# - platform: radarr
#  host: radarr # !secret ip_vault
#  api_key: !secret api_key_radarr
#  days: 30
#  monitored_conditions:
#    - movies
#    - upcoming
# - platform: pyload
#  host: !secret ip_vault
#  username: !secret pyload_user
#  password: !secret pyload_pass

automation:
  - alias: Plex bandwidth throttle
    trigger:
      - platform: numeric_state
        entity_id: sensor.tautulli_wan_bandwidth
        above: 10
      - platform: numeric_state
        entity_id: sensor.tautulli_wan_bandwidth
        below: 10
        for:
          minutes: 5
      - platform: time
        at:
          - "02:00:00"
          - "06:00:00"
    action:
      - service: rtorrent.set_upload_speed
        data_template:
          speed: >
            {% if states('sensor.tautulli_wan_bandwidth')|float > 10 %}
              100
            {% elif now() >= now().replace(hour=1, minute=59, second=0) and
                now() < now().replace(hour=5, minute=59, second=0) %}
              3000
            {% else %}
              1000
            {% endif %}
