homeassistant:
  customize:
    media_player.tv:
      icon: mdi:television

samsungtv:
  name: TV
  host: !secret ip_tv_samsung
  turn_on_action:
    - service: kodi.call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate

# media_player:
#   - platform: samsungtv_custom
#     host: !secret ip_tv_samsung
#     mac: !secret mac_tv_samsung_lan
#     port: 8001
#     sourcelist: '{"HDMI1": "KEY_HDMI1", "HDMI2": "KEY_HDMI2", "HDMI3": "KEY_HDMI3", "TV": "KEY_TV"}'
#     protocol: ctl_beta

switch:
  - platform: template
    switches:
      tv:
        friendly_name: TV
        value_template: "{{ is_state('media_player.tv', 'on') }}"
        turn_on:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi
            method: Addons.ExecuteAddon
            addonid: script.json-cec
            params:
              command: activate
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.tv
        icon_template: >-
          {% if is_state('media_player.tv', 'on') %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}
        # turn_off:
        #   service: media_player.kodi_call_method
        #   data:
        #     entity_id: media_player.kodi
        #     method: Addons.ExecuteAddon
        #     addonid: script.json-cec
        #     params:
        #       command: standby
