sensor:
  - platform: history_stats
    name: Washing machine runtime today
    entity_id: binary_sensor.washing_machine
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    # start: '{{ (as_timestamp(now() - 24 * 3600) }}'
    end: "{{ now() }}"

automation:
  - alias: Washing machine started mobile
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "off"
        to: "on"
    action:
      - service: telegram_bot.send_message
        data_template:
          disable_notification: true
          message: Washing machine started
      - service: notify.mobile_app_disrupted_iphone
        data_template:
          data:
            push:
              thread-id: "washing_machine"
          message: Washing machine started

  - alias: Washing machine finished
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "on"
        to: "off"
    # condition:
    #   - condition: template # needs to have run for at least 15min otherwise it's likely a false positive
    #     value_template: "{{ (as_timestamp(now()) - state_attr('input_datetime.washing_machine_started', 'timestamp')) > 15 * 60 }}"
    action:
      - service: notify.all_iphones
        data_template:
          data:
            push:
              thread-id: "washing_machine"
          title: >
            Washing machine is done 👚👕
