homeassistant:
  customize:
    sensor.washing_machine_runtime:
      icon: mdi:timer-outline

input_datetime:
  washing_machine_started:
    name: Washing machine last started
    has_date: true
    has_time: true

  washing_machine_finished:
    name: Washing machine last finished
    has_date: true
    has_time: true

sensor:
  - platform: history_stats
    name: Washing machine runtime today
    entity_id: binary_sensor.washing_machine
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    # start: '{{ (as_timestamp(now() - 24 * 3600) }}'
    end: "{{ now() }}"

  # - platform: template
  #   sensors:
  #     washing_machine_runtime:
  #       friendly_name: Washing machine runtime
  #       unit_of_measurement: h
  #       value_template: >
  #         {% if is_state("binary_sensor.washing_machine", "on") %}
  #           {{ (as_timestamp(now()) - state_attr('input_datetime.washing_machine_started', 'timestamp') | int) | timestamp_custom('%-H:%M', False) }}
  #         {% else %}
  #           {{ ((state_attr('input_datetime.washing_machine_finished', 'timestamp') | int) - (state_attr('input_datetime.washing_machine_started', 'timestamp') | int)) | timestamp_custom('%-H:%M', False) }}
  #         {% endif %}

automation:
  - alias: Washing machine started mobile
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "off"
        to: "on"
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.washing_machine_started
        data_template:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      - service: automation.turn_on
        entity_id: automation.washing_machine_update_runtime
      - service: telegram_bot.send_message
        data_template:
          disable_notification: true
          message: Washing machine started
      - service: notify.mobile_app_disrupted_iphone
        data_template:
          data:
            push:
              thread-id: "washing_machine"
          message: Washing machine started

  - alias: Washing machine finished mobile
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "on"
        to: "off"
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.washing_machine_finished
        data_template:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      # - service: automation.turn_off
      #   entity_id: automation.washing_machine_update_runtime
      - service: homeassistant.update_entity
        entity_id: sensor.washing_machine_runtime
      - service: telegram_bot.send_message
        data:
          message: "Washing machine finished"
      - service: notify.mobile_app_disrupted_iphone
        data_template:
          data:
            push:
              thread-id: "washing_machine"
          message: >
            Washing machine is done 👚👕

  - alias: Washing machine finished
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "on"
        to: "off"
    condition:
      - condition: template # needs to have run for at least 15min otherwise it's likely a false positive
        value_template: "{{ (as_timestamp(now()) - state_attr('input_datetime.washing_machine_started', 'timestamp')) > 15 * 60 }}"
    action:
      - delay: "00:00:01"
      - service: notify.all_iphones
        data_template:
          data:
            push:
              thread-id: "washing_machine"
          title: >
            Washing machine is done 👚👕
          # message: >
          #   took {{ states('sensor.washing_machine_runtime') }} h

  - alias: Washing machine update runtime
    trigger:
      # every minute
      - platform: time_pattern
        minutes: "/1"
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.washing_machine_runtime

  - alias: Washing machine update runtime off
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        from: "on"
        to: "off"
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: automation.washing_machine_update_runtime
        state: "on"
      - condition: state
        entity_id: binary_sensor.washing_machine
        state: "off"
    action:
      - service: automation.turn_off
        entity_id: automation.washing_machine_update_runtime
